"""Hand approach poses and twists for each test object.

For each object, defines a canonical hand approach:
  - pose: hand position ~15cm away from the object, oriented toward it
  - twist: small forward linear velocity, near-zero angular velocity

The SMC sampler's ROI prediction must cover the object for the planner
to work. These poses may need iterative tuning — run with debug_visualization
enabled and verify the ROI covers the object.
"""

import numpy as np

# Grasp approach poses are defined in world frame.
# The hand approaches from the -X direction (or similar), moving toward +X.
# Object centers are at or near the origin (as generated by generate_objects.py).

APPROACHES = {
    # ---- Parametric objects ----
    "cylinder_upright": {
        # Hand 15cm in front, same height, pointing forward
        "pose": {"px": -0.15, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        # Moving forward at 10 cm/s
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "cylinder_tilted": {
        "pose": {"px": -0.15, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "ellipsoid": {
        "pose": {"px": -0.15, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "tapered_bottle": {
        # Bottle is taller (18cm), approach from slightly below center
        "pose": {"px": -0.15, "py": 0.0, "pz": -0.02,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "l_block": {
        # L-block has parts at different heights, approach from front
        "pose": {"px": -0.15, "py": 0.0, "pz": 0.01,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "small_cube": {
        # Small object — approach closer
        "pose": {"px": -0.12, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.08, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "thin_plate": {
        # Plate is flat on table, approach from front, slightly above
        "pose": {"px": -0.15, "py": 0.0, "pz": 0.005,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },

    # ---- YCB objects ----
    "banana": {
        "pose": {"px": -0.15, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "mug": {
        # Approach from the side where the handle is
        "pose": {"px": -0.15, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "power_drill": {
        # Approach the handle area
        "pose": {"px": -0.15, "py": 0.0, "pz": -0.03,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },

    # ---- YCB fallbacks ----
    "banana_fallback": {
        "pose": {"px": -0.15, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "mug_fallback": {
        "pose": {"px": -0.15, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "drill_fallback": {
        "pose": {"px": -0.15, "py": 0.0, "pz": -0.03,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
}


def get_approach(object_name: str) -> dict:
    """Get the hand approach for an object.

    Returns dict with 'pose' and 'twist' sub-dicts.
    Raises KeyError if object has no defined approach.
    """
    if object_name not in APPROACHES:
        raise KeyError(
            f"No approach defined for '{object_name}'. "
            f"Available: {sorted(APPROACHES.keys())}"
        )
    return APPROACHES[object_name]
