"""Hand approach poses and twists for each test object.

For each object, defines a canonical hand approach:
  - pose: hand position ~25cm away from the object (grasp-planning distance),
    oriented toward it. This distance is chosen so that the wrist-mounted camera
    (16cm above the palm, 15-deg downward pitch) can see the upper portion of
    the object, while the head camera sees the full object from above.
  - twist: small forward linear velocity, near-zero angular velocity

The SMC sampler's ROI prediction must cover the object for the planner
to work. These poses may need iterative tuning — run with debug_visualization
enabled and verify the ROI covers the object.
"""

import numpy as np

# Grasp approach poses are defined in world frame.
# The hand approaches from the -X direction (or similar), moving toward +X.
# Object centers are at or near the origin (as generated by generate_objects.py).
#
# Approach distance is ~25cm (grasp-planning distance). This is the distance
# at which the multi-view system observes the object before committing to a
# grasp trajectory. The wrist camera at 16cm above the palm with a 15-degree
# downward pitch can see the upper portion of objects at this distance.

# Default approach distance for most objects
_DEFAULT_DIST = -0.25  # 25cm in front of object

APPROACHES = {
    # ---- Parametric objects ----
    "cylinder_upright": {
        # Hand 25cm in front, same height, pointing forward
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        # Moving forward at 10 cm/s
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "cylinder_tilted": {
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "ellipsoid": {
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "tapered_bottle": {
        # Bottle is taller (18cm), approach from slightly below center
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": -0.02,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "l_block": {
        # L-block has parts at different heights, approach from front
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.01,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "small_cube": {
        # Small object — approach slightly closer
        "pose": {"px": -0.20, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.08, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "thin_plate": {
        # Plate is flat on table, approach from front, slightly above
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.005,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },

    # ---- Non-convex parametric objects ----
    "mug_with_handle": {
        # Approach from the handle side
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "notched_box": {
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "cross_shape": {
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },

    # ---- YCB objects ----
    "banana": {
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "mug": {
        # Approach from the side where the handle is
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "power_drill": {
        # Approach the handle area
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": -0.03,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },

    # ---- YCB fallbacks ----
    "banana_fallback": {
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "mug_fallback": {
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": 0.0,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
    "drill_fallback": {
        "pose": {"px": _DEFAULT_DIST, "py": 0.0, "pz": -0.03,
                 "qx": 0.0, "qy": 0.0, "qz": 0.0, "qw": 1.0},
        "twist": {"lx": 0.10, "ly": 0.0, "lz": 0.0,
                  "ax": 0.0, "ay": 0.0, "az": 0.0},
    },
}


def get_approach(object_name: str) -> dict:
    """Get the hand approach for an object.

    Returns dict with 'pose' and 'twist' sub-dicts.
    Raises KeyError if object has no defined approach.
    """
    if object_name not in APPROACHES:
        raise KeyError(
            f"No approach defined for '{object_name}'. "
            f"Available: {sorted(APPROACHES.keys())}"
        )
    return APPROACHES[object_name]
