"""Object registry — loads point clouds and metadata for test objects.

Searches for .npz files in:
  1. objects/parametric/  (generated by generate_objects.py)
  2. objects/ycb/         (generated from YCB meshes or fallbacks)

Each .npz contains:
  - points: (N, 3) float32 surface points
  - metadata: JSON string with name, expected_grasp, dimensions
"""

import json
import os
from typing import Optional

import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PARAMETRIC_DIR = os.path.join(SCRIPT_DIR, "objects", "parametric")
YCB_DIR = os.path.join(SCRIPT_DIR, "objects", "ycb")

# Convexity classification for each object.
# Convex objects have no self-occlusion from any single viewpoint.
# Non-convex objects have concavities, handles, or overhangs that create
# self-occlusion — these are where the multi-view advantage is strongest.
CONVEXITY = {
    # Convex parametric objects
    "cylinder_upright": "convex",
    "cylinder_tilted": "convex",
    "ellipsoid": "convex",
    "tapered_bottle": "convex",
    "small_cube": "convex",
    # Non-convex parametric objects
    "cross_shape": "non-convex",
    # YCB objects (non-convex geometry)
    "banana": "non-convex",
    "mug": "non-convex",
    "power_drill": "non-convex",
}


def get_convexity(name: str) -> str:
    """Return 'convex' or 'non-convex' for the given object."""
    return CONVEXITY.get(name, "unknown")


def _discover_objects() -> dict[str, str]:
    """Scan directories for .npz object files.

    Returns dict mapping object_name -> file_path.
    """
    objects = {}
    for search_dir in [PARAMETRIC_DIR, YCB_DIR]:
        if not os.path.isdir(search_dir):
            continue
        for fname in sorted(os.listdir(search_dir)):
            if fname.endswith(".npz"):
                name = fname[:-4]  # strip .npz
                objects[name] = os.path.join(search_dir, fname)
    return objects


_OBJECT_CACHE: Optional[dict[str, str]] = None


def list_objects() -> list[str]:
    """Return sorted list of available object names."""
    global _OBJECT_CACHE
    if _OBJECT_CACHE is None:
        _OBJECT_CACHE = _discover_objects()
    return sorted(_OBJECT_CACHE.keys())


def load_object(name: str) -> dict:
    """Load an object's point cloud and metadata.

    Args:
        name: Object name (e.g. "cylinder_upright", "banana")

    Returns:
        dict with:
            name: str
            points: (N, 3) float32 array
            expected_grasp: str ("cylindrical", "pinch", "lateral")
            dimensions: dict
            n_points: int
            source_file: str
    """
    global _OBJECT_CACHE
    if _OBJECT_CACHE is None:
        _OBJECT_CACHE = _discover_objects()

    if name not in _OBJECT_CACHE:
        available = list_objects()
        raise KeyError(
            f"Object '{name}' not found. Available: {available}"
        )

    path = _OBJECT_CACHE[name]
    data = np.load(path, allow_pickle=True)
    points = data["points"].astype(np.float32)

    # Parse metadata
    meta_raw = str(data["metadata"][0])
    meta = json.loads(meta_raw)

    return {
        "name": meta.get("name", name),
        "points": points,
        "expected_grasp": meta.get("expected_grasp", "cylindrical"),
        "dimensions": meta.get("dimensions", {}),
        "n_points": len(points),
        "source_file": path,
    }


def load_all_objects() -> dict[str, dict]:
    """Load all available objects.

    Returns dict mapping object_name -> object_dict.
    """
    result = {}
    for name in list_objects():
        try:
            result[name] = load_object(name)
        except Exception as e:
            print(f"WARNING: Failed to load {name}: {e}")
    return result
