#!/usr/bin/env python3
"""
Verification script for contact LUT file.

Validates the dual-quaternion LUT generated by model.py.
"""

import os
import numpy as np

DATA_DIR = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "data"))
LUT_PATH = os.path.join(DATA_DIR, "finger_contact_lut.npz")

REQUIRED_KEYS = [
    "meta_version",
    "representation",
    "resolution",
    "joint_names",
    "joint_limits_lower",
    "joint_limits_upper",
    "thumb_opposition_states",
    "all_contact_names",
    "all_contact_geometry_names",
    "all_contact_groups",
    "all_contact_local_offsets",
    "index_contact_names",
    "mrl_contact_names",
    "thumb_contact_names",
    "palm_contact_names",
    "index_table",
    "mrl_table",
    "thumb_flex_table",
    "thumb_opp_mode0_table",
    "thumb_opp_mode1_table",
    "palm_table",
]


def _is_close(a, b, tol=1e-5):
    return abs(float(a) - float(b)) <= tol

def print_structure(f):
    """Print structure of .npz file showing all arrays."""
    print("\n" + "=" * 60)
    print("LUT FILE STRUCTURE")
    print("=" * 60)

    for key in sorted(f.files):
        arr = f[key]
        print(f"[ARRAY] {key} - shape: {arr.shape}, dtype: {arr.dtype}")


def verify_required_keys(f):
    """Verify all expected arrays are present."""
    print("\n" + "=" * 60)
    print("REQUIRED KEY VERIFICATION")
    print("=" * 60)

    ok = True
    missing = []
    for key in REQUIRED_KEYS:
        if key not in f.files:
            missing.append(key)
            ok = False

    if missing:
        print("FAIL Missing keys:")
        for key in missing:
            print(f"  - {key}")
    else:
        print("PASS All required keys present")

    return ok


def verify_metadata(f):
    """Validate metadata content and basic shapes."""
    print("\n" + "=" * 60)
    print("METADATA VERIFICATION")
    print("=" * 60)

    ok = True

    representation = f["representation"]
    rep = str(representation[0]) if representation.size else ""
    print(f"representation: {rep}")
    if rep != "dual_quaternion_wxyz":
        print("FAIL Unexpected representation value")
        ok = False

    resolution_arr = f["resolution"]
    if resolution_arr.shape != (1,):
        print(f"FAIL resolution shape expected (1,), got {resolution_arr.shape}")
        ok = False
        resolution = 0
    else:
        resolution = int(resolution_arr[0])
        print(f"resolution: {resolution}")
        if resolution <= 0:
            print("FAIL resolution must be positive")
            ok = False

    joint_names = f["joint_names"]
    lower = f["joint_limits_lower"]
    upper = f["joint_limits_upper"]
    if lower.shape != upper.shape or lower.shape != joint_names.shape:
        print("FAIL joint limits/joint names shape mismatch")
        ok = False
    else:
        if np.any(lower > upper):
            print("FAIL some joint lower limits exceed upper limits")
            ok = False
        else:
            print("PASS joint limit bounds look valid")

    thumb_states = f["thumb_opposition_states"]
    if thumb_states.shape != (2,):
        print(f"FAIL thumb_opposition_states shape expected (2,), got {thumb_states.shape}")
        ok = False
    elif not np.all((thumb_states >= 0.0) & (thumb_states <= 1.0)):
        print("FAIL thumb_opposition_states must be in [0, 1]")
        ok = False
    else:
        print(f"PASS thumb_opposition_states: {thumb_states}")

    return ok, resolution


def verify_contact_metadata_consistency(f):
    """Validate contact name/group arrays are internally consistent."""
    print("\n" + "=" * 60)
    print("CONTACT METADATA CONSISTENCY")
    print("=" * 60)

    ok = True

    all_names = f["all_contact_names"]
    all_geoms = f["all_contact_geometry_names"]
    all_groups = f["all_contact_groups"]
    all_offsets = f["all_contact_local_offsets"]

    n_all = all_names.shape[0]
    if all_geoms.shape[0] != n_all or all_groups.shape[0] != n_all or all_offsets.shape[0] != n_all:
        print("FAIL all_contact_* arrays have mismatched lengths")
        return False

    if all_offsets.shape[1:] != (3,):
        print(f"FAIL all_contact_local_offsets must be (N,3), got {all_offsets.shape}")
        ok = False

    unique_name_count = len(set(all_names.tolist()))
    if unique_name_count != n_all:
        print("FAIL all_contact_names contains duplicates")
        ok = False

    group_map = {
        "index": f["index_contact_names"],
        "mrl": f["mrl_contact_names"],
        "thumb": f["thumb_contact_names"],
        "palm": f["palm_contact_names"],
    }
    all_name_set = set(all_names.tolist())
    for group_name, names in group_map.items():
        names_set = set(names.tolist())
        if not names_set.issubset(all_name_set):
            print(f"FAIL {group_name}_contact_names contains names not in all_contact_names")
            ok = False

    print("PASS" if ok else "FAIL", "contact metadata consistency")
    return ok


def _dq_to_se3(dq):
    """Convert dual quaternion [qr_w,qr_x,qr_y,qr_z,qd_w,qd_x,qd_y,qd_z] to 4x4 transform."""
    dq = np.asarray(dq, dtype=float)
    qr = dq[:4]
    qd = dq[4:]

    qr_norm = np.linalg.norm(qr)
    if qr_norm <= 1e-12:
        raise ValueError("Zero-norm real quaternion")
    qr = qr / qr_norm

    w, x, y, z = qr
    rot = np.array(
        [
            [1.0 - 2.0 * (y * y + z * z), 2.0 * (x * y - z * w), 2.0 * (x * z + y * w)],
            [2.0 * (x * y + z * w), 1.0 - 2.0 * (x * x + z * z), 2.0 * (y * z - x * w)],
            [2.0 * (x * z - y * w), 2.0 * (y * z + x * w), 1.0 - 2.0 * (x * x + y * y)],
        ],
        dtype=float,
    )

    qr_conj = np.array([w, -x, -y, -z], dtype=float)

    def qmul(a, b):
        aw, ax, ay, az = a
        bw, bx, by, bz = b
        return np.array(
            [
                aw * bw - ax * bx - ay * by - az * bz,
                aw * bx + ax * bw + ay * bz - az * by,
                aw * by - ax * bz + ay * bw + az * bx,
                aw * bz + ax * by - ay * bx + az * bw,
            ],
            dtype=float,
        )

    t_quat = 2.0 * qmul(qd, qr_conj)
    trans = t_quat[1:]

    T = np.eye(4, dtype=float)
    T[:3, :3] = rot
    T[:3, 3] = trans
    return T


def verify_dual_quaternion_table(table, table_name):
    """Check table shape, finite values, and DQ constraints."""
    ok = True

    if table.ndim not in (2, 3):
        print(f"FAIL {table_name}: expected ndim 2 or 3, got {table.ndim}")
        return False
    if table.shape[-1] != 8:
        print(f"FAIL {table_name}: last dimension must be 8, got {table.shape[-1]}")
        return False
    if not np.all(np.isfinite(table)):
        print(f"FAIL {table_name}: contains non-finite values")
        return False

    flat = table.reshape(-1, 8)
    qr = flat[:, :4]
    qd = flat[:, 4:]

    qr_norm = np.linalg.norm(qr, axis=1)
    if np.any(np.abs(qr_norm - 1.0) > 2e-3):
        bad = int(np.argmax(np.abs(qr_norm - 1.0) > 2e-3))
        print(f"FAIL {table_name}: non-unit real quaternion near row {bad}")
        ok = False

    orth = np.sum(qr * qd, axis=1)
    if np.any(np.abs(orth) > 2e-3):
        bad = int(np.argmax(np.abs(orth) > 2e-3))
        print(f"FAIL {table_name}: q_real dot q_dual not near zero near row {bad}")
        ok = False

    # Spot-check reconstructed SE3 validity.
    for idx in np.linspace(0, flat.shape[0] - 1, num=min(5, flat.shape[0]), dtype=int):
        try:
            T = _dq_to_se3(flat[idx])
        except Exception as exc:
            print(f"FAIL {table_name}: could not reconstruct SE3 at row {idx}: {exc}")
            ok = False
            continue

        R = T[:3, :3]
        should_be_I = R.T @ R
        det = np.linalg.det(R)
        if not np.allclose(should_be_I, np.eye(3), atol=1e-3):
            print(f"FAIL {table_name}: non-orthonormal rotation at row {idx}")
            ok = False
        if not _is_close(det, 1.0, tol=1e-3):
            print(f"FAIL {table_name}: rotation determinant not 1 at row {idx}")
            ok = False

    if ok:
        print(f"PASS {table_name}: dual quaternion checks")
    return ok


def verify_table_dimensions(f, resolution):
    """Validate table shapes against contact-name arrays and resolution."""
    print("\n" + "=" * 60)
    print("TABLE DIMENSION VERIFICATION")
    print("=" * 60)

    ok = True

    shape_expectations = [
        ("index_table", (resolution, f["index_contact_names"].shape[0], 8)),
        ("mrl_table", (resolution, f["mrl_contact_names"].shape[0], 8)),
        ("thumb_flex_table", (resolution, f["thumb_contact_names"].shape[0], 8)),
        ("thumb_opp_mode0_table", (resolution, f["all_contact_names"].shape[0], 8)),
        ("thumb_opp_mode1_table", (resolution, f["all_contact_names"].shape[0], 8)),
        ("palm_table", (f["palm_contact_names"].shape[0], 8)),
    ]

    for key, expected_shape in shape_expectations:
        actual_shape = f[key].shape
        if actual_shape != expected_shape:
            print(f"FAIL {key}: expected {expected_shape}, got {actual_shape}")
            ok = False
        else:
            print(f"PASS {key}: {actual_shape}")

    return ok


def verify_mode_consistency(f):
    """Check thumb mode tables behave as expected."""
    print("\n" + "=" * 60)
    print("THUMB MODE CONSISTENCY")
    print("=" * 60)

    ok = True

    mode0 = f["thumb_opp_mode0_table"]
    mode1 = f["thumb_opp_mode1_table"]
    groups = f["all_contact_groups"]

    thumb_mask = groups == "thumb"
    non_thumb_mask = np.logical_not(thumb_mask)

    if not np.any(thumb_mask):
        print("FAIL no thumb contacts in all_contact_groups")
        return False

    thumb_delta = np.max(np.abs(mode0[:, thumb_mask, :] - mode1[:, thumb_mask, :]))
    if thumb_delta < 1e-6:
        print("FAIL thumb mode tables appear identical on thumb contacts")
        ok = False
    else:
        print(f"PASS thumb contacts differ across modes (max delta {thumb_delta:.3e})")

    if np.any(non_thumb_mask):
        non_thumb_delta = np.max(np.abs(mode0[:, non_thumb_mask, :] - mode1[:, non_thumb_mask, :]))
        print(f"INFO non-thumb max delta across thumb modes: {non_thumb_delta:.3e}")

    return ok


def demonstrate_lookup(f):
    """Print a few lookup examples from the tables."""
    print("\n" + "=" * 60)
    print("LOOKUP DEMONSTRATION")
    print("=" * 60)

    i = min(3, f["index_table"].shape[0] - 1)
    j = min(1, f["index_table"].shape[1] - 1)
    print(f"index_table[{i}, {j}] DQ: {f['index_table'][i, j]}")

    i = min(5, f["thumb_flex_table"].shape[0] - 1)
    j = min(2, f["thumb_flex_table"].shape[1] - 1)
    print(f"thumb_flex_table[{i}, {j}] DQ: {f['thumb_flex_table'][i, j]}")

    i = min(4, f["thumb_opp_mode1_table"].shape[0] - 1)
    j = min(10, f["thumb_opp_mode1_table"].shape[1] - 1)
    print(f"thumb_opp_mode1_table[{i}, {j}] DQ: {f['thumb_opp_mode1_table'][i, j]}")


def verify_all_dq_tables(f):
    """Run DQ checks across all stored transform arrays."""
    print("\n" + "=" * 60)
    print("DUAL QUATERNION VALIDATION")
    print("=" * 60)

    ok = True
    for key in [
        "index_table",
        "mrl_table",
        "thumb_flex_table",
        "thumb_opp_mode0_table",
        "thumb_opp_mode1_table",
        "palm_table",
    ]:
        ok = verify_dual_quaternion_table(f[key], key) and ok
    return ok


def _dq_translation(dq):
    """Extract translation vector from dual quaternion (via SE3 conversion)."""
    T = _dq_to_se3(dq)
    return T[:3, 3]


def _jump_stats_from_table(table):
    """Compute adjacent-sample jump distances for a table of shape (S, C, 8)."""
    if table.ndim != 3 or table.shape[0] < 2:
        return np.array([], dtype=float)

    samples, contacts, _ = table.shape
    jumps = np.empty((samples - 1) * contacts, dtype=float)
    idx = 0
    for i in range(samples - 1):
        for j in range(contacts):
            p0 = _dq_translation(table[i, j])
            p1 = _dq_translation(table[i + 1, j])
            jumps[idx] = np.linalg.norm(p1 - p0)
            idx += 1
    return jumps


def verify_discretization_jump_lengths(f):
    """Measure positional jump distances between adjacent control samples."""
    print("\n" + "=" * 60)
    print("DISCRETIZATION JUMP LENGTHS")
    print("=" * 60)

    table_keys = [
        "index_table",
        "mrl_table",
        "thumb_flex_table",
        "thumb_opp_mode0_table",
        "thumb_opp_mode1_table",
    ]

    all_jumps = []
    per_table = {}

    zero_tol_m = 1e-9

    for key in table_keys:
        table = f[key]
        jumps = _jump_stats_from_table(table)
        per_table[key] = jumps
        if jumps.size == 0:
            print(f"INFO {key}: no adjacent jumps to evaluate")
            continue

        moving = jumps[jumps > zero_tol_m]
        zero_count = int(jumps.size - moving.size)
        if moving.size > 0:
            all_jumps.append(moving)
            print(
                f"{key}: count={moving.size}, zeros_removed={zero_count}, "
                f"min={moving.min() * 1000.0:.3f} mm, max={moving.max() * 1000.0:.3f} mm, "
                f"median={np.median(moving) * 1000.0:.3f} mm, mean={moving.mean() * 1000.0:.3f} mm"
            )
        else:
            print(f"INFO {key}: all {zero_count} jumps were zero and removed")

    if all_jumps:
        all_concat = np.concatenate(all_jumps)
        print("-" * 60)
        print(
            "overall (non-zero only): "
            f"count={all_concat.size}, "
            f"min={all_concat.min() * 1000.0:.3f} mm, max={all_concat.max() * 1000.0:.3f} mm, "
            f"median={np.median(all_concat) * 1000.0:.3f} mm, mean={all_concat.mean() * 1000.0:.3f} mm"
        )
    else:
        all_concat = np.array([], dtype=float)
        print("INFO No non-zero jump distances were found")

    # Palm table is static by design (no discretization axis), report spread only.
    palm = f["palm_table"]
    palm_pts = np.array([_dq_translation(dq) for dq in palm], dtype=float)
    palm_center = np.mean(palm_pts, axis=0)
    palm_r = np.linalg.norm(palm_pts - palm_center, axis=1)
    print(
        f"palm_table: static points={len(palm_pts)}, "
        f"radius range=[{palm_r.min() * 1000.0:.3f}, {palm_r.max() * 1000.0:.3f}] mm, "
        f"median radius={np.median(palm_r) * 1000.0:.3f} mm, mean radius={palm_r.mean() * 1000.0:.3f} mm"
    )

    return {
        "per_table": per_table,
        "overall": all_concat,
    }


def verify_contact_bbox(f):
    """Compute axis-aligned bbox over all contact points in LUT tables."""
    print("\n" + "=" * 60)
    print("CONTACT POINT BBOX")
    print("=" * 60)

    table_keys = [
        "index_table",
        "mrl_table",
        "thumb_flex_table",
        "thumb_opp_mode0_table",
        "thumb_opp_mode1_table",
        "palm_table",
    ]

    points = []
    for key in table_keys:
        arr = f[key]
        if arr.ndim == 3:
            flat = arr.reshape(-1, 8)
        elif arr.ndim == 2:
            flat = arr
        else:
            continue
        points.extend([_dq_translation(dq) for dq in flat])

    if not points:
        print("INFO no points found for bbox")
        return None

    pts = np.array(points, dtype=float)
    p_min = np.min(pts, axis=0)
    p_max = np.max(pts, axis=0)
    span = p_max - p_min

    print(
        "bbox min [mm]: "
        f"x={p_min[0] * 1000.0:.3f}, y={p_min[1] * 1000.0:.3f}, z={p_min[2] * 1000.0:.3f}"
    )
    print(
        "bbox max [mm]: "
        f"x={p_max[0] * 1000.0:.3f}, y={p_max[1] * 1000.0:.3f}, z={p_max[2] * 1000.0:.3f}"
    )
    print(
        "bbox span [mm]: "
        f"dx={span[0] * 1000.0:.3f}, dy={span[1] * 1000.0:.3f}, dz={span[2] * 1000.0:.3f}"
    )
    print(f"samples used: {len(points)}")

    return {
        "min": p_min,
        "max": p_max,
        "span": span,
        "count": len(points),
    }

def main():
    """Main verification function."""
    print("=" * 60)
    print("FINGER CONTACT LUT VERIFICATION")
    print("=" * 60)
    print(f"LUT Path: {LUT_PATH}")

    if not os.path.exists(LUT_PATH):
        print(f"\nFAIL LUT file not found at {LUT_PATH}")
        return False

    try:
        f = np.load(LUT_PATH, allow_pickle=False)
        print("\nPASS LUT file loaded successfully")

        print_structure(f)

        keys_ok = verify_required_keys(f)
        if not keys_ok:
            f.close()
            return False

        metadata_ok, resolution = verify_metadata(f)
        contact_meta_ok = verify_contact_metadata_consistency(f)
        dims_ok = verify_table_dimensions(f, resolution)
        dq_ok = verify_all_dq_tables(f)
        mode_ok = verify_mode_consistency(f)
        jump_stats = verify_discretization_jump_lengths(f)
        bbox_stats = verify_contact_bbox(f)

        demonstrate_lookup(f)

        f.close()

        all_ok = keys_ok and metadata_ok and contact_meta_ok and dims_ok and dq_ok and mode_ok

        print("\n" + "=" * 60)
        print("VERIFICATION SUMMARY")
        print("=" * 60)
        print(f"required_keys_ok:        {keys_ok}")
        print(f"metadata_ok:             {metadata_ok}")
        print(f"contact_metadata_ok:     {contact_meta_ok}")
        print(f"table_dimensions_ok:     {dims_ok}")
        print(f"dual_quaternion_ok:      {dq_ok}")
        print(f"thumb_mode_consistency:  {mode_ok}")
        print(f"jump_samples_count:      {jump_stats['overall'].size}")
        print(f"bbox_samples_count:      {0 if bbox_stats is None else bbox_stats['count']}")
        print(f"resolution:              {resolution}")
        print(f"\nOverall: {'PASS' if all_ok else 'FAIL'}")
        return all_ok

    except Exception as e:
        print(f"\nFAIL Failed to verify LUT file: {e}")
        import traceback

        traceback.print_exc()
        return False


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
