# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - thumb_trajectory_controller
    - index_trajectory_controller
    - mrl_trajectory_controller

  thumb_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - j_thumb_fle
    action_ns: follow_joint_trajectory
    default: true
  index_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - j_index_fle
    action_ns: follow_joint_trajectory
    default: true
  mrl_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - j_mrl_fle
    action_ns: follow_joint_trajectory
    default: true
