# IMU rate set to 15 Hz to match camera FPS
/**:
  ros__parameters:
    bus: 7
    imu_i2c_address: 104
    frame_id: "cam0_imu_link"
    imu_rate_hz: 15.0
    accel_range_g: 2
    gyro_range_dps: 250
    publish_temperature_in_imu_msg: true