# syntax=docker/dockerfile:1
FROM docker.io/ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
        ros-humble-realsense2-camera \
        ros-humble-realsense2-description \
        ros-humble-rmw-cyclonedds-cpp \
        ros-humble-tf2-sensor-msgs \
        ros-humble-sensor-msgs-py \
        ros-humble-launch-ros \
        python3-pip

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install numpy

WORKDIR /ros_ws
COPY launch/ /ros_ws/launch/
COPY nodes/  /ros_ws/nodes/

ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp
# ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST causes issues with FastDDS.

ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && exec \"$@\"", "--"]
CMD ["ros2", "launch", "/ros_ws/launch/multiview_full_launch.py"]
