# syntax=docker/dockerfile:1
FROM docker.io/ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        ros-humble-rviz2 \
        ros-humble-rmw-fastrtps-cpp \
        ros-humble-tf2-sensor-msgs \
        ros-humble-launch-ros \
    && rm -rf /var/lib/apt/lists/*

ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp

RUN mkdir -p /rviz_config
COPY config/realsense_pointcloud.rviz /rviz_config/

CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && exec rviz2 -d /rviz_config/realsense_pointcloud.rviz"]
