FROM docker.io/ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        ros-humble-realsense2-camera \
        ros-humble-realsense2-description \
        ros-humble-rmw-cyclonedds-cpp \
        ros-humble-tf2-sensor-msgs \
        ros-humble-sensor-msgs-py \
        ros-humble-launch-ros \
        python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir numpy

WORKDIR /ros_ws
COPY launch/ /ros_ws/launch/
COPY nodes/  /ros_ws/nodes/

ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
ENV ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST

ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && exec \"$@\"", "--"]
CMD ["ros2", "launch", "/ros_ws/launch/two_d435_launch.py"]
