uint32 MOTOR_THUMB=0
uint32 MOTOR_INDEX=1
uint32 MOTOR_MRL=2

uint32 motor  # Target motor number. 0: thumb, 1: index, 2: mrl.
---
int32 open_mpos   # OPEN motor position
int32 close_mpos  # CLOSE motor position

bool success        # True, if reading was successful, false if not
string err_message  # Error message, in case of failure
