cameras:
  head:
    namespace: head
    name: d435i_head
    serial_no: "_829212072207"
    mount_location: forehead
  arm:
    namespace: arm
    name: d435i_arm
    serial_no: "_827112072033"
    mount_location: prosthetic_arm

common:
  pointcloud_enable: true
  align_depth_enable: true
  enable_gyro: true
  enable_accel: true
  unite_imu_method: 2
  depth_profile: "640x480x30"
  color_profile: "640x480x30"
  pointcloud_neon_param: "pointcloud__neon_.enable"
  pointcloud_neon_value: true
  pointcloud_neon_delay_sec: 6.0
