---
int32 thumb_nfor  # Thumb normal force
int32 index_nfor  # Index normal force
int32 mrl_nfor    # Mrl normal force

int32 thumb_tfor  # Thumb tangential force
int32 index_tfor  # Index tangential force
int32 mrl_tfor    # Mrl tangential force

bool success        # True, if data reading was successful, false if not
string err_message  # Error message, in case of failure
