#!/bin/bash
# menu_haptic_test.sh — Interactive parameter editor for option 4 (haptic force test).
#
# Usage: bash scripts/menu_haptic_test.sh
# On space: writes env to /tmp/haptic_test_env.sh and exits 0
# On q:     exits 1
set -e

# ── Defaults ─────────────────────────────────────────────────────────
MIA_PORT="${MIA_PORT:-/dev/ttyUSB0}"
WRIST_PORT="${WRIST_PORT:-/dev/ttyUSB1}"
MOCK_HARDWARE="${MOCK_HARDWARE:-auto}"
WRIST_ENABLE="${WRIST_ENABLE:-auto}"
HAPTIC_ENABLE="${HAPTIC_ENABLE:-true}"
FORCE_RETRAIN="${FORCE_RETRAIN:-false}"
AUTO_KILL_S="${AUTO_KILL_S:-0}"
CONFIG_PATH="${CONFIG_PATH:-config/mia_haptic_force_test.yaml}"

# ── Parameter list ───────────────────────────────────────────────────
PARAMS=(MIA_PORT WRIST_PORT MOCK_HARDWARE WRIST_ENABLE HAPTIC_ENABLE FORCE_RETRAIN AUTO_KILL_S CONFIG_PATH)
NUM_PARAMS=${#PARAMS[@]}

declare -A PARAM_DESC
PARAM_DESC[MIA_PORT]="Mia hand serial port"
PARAM_DESC[WRIST_PORT]="Wrist Dynamixel port"
PARAM_DESC[MOCK_HARDWARE]="auto|true|false — force mock hardware"
PARAM_DESC[WRIST_ENABLE]="auto|true|false — enable wrist"
PARAM_DESC[HAPTIC_ENABLE]="true|false — enable Vibro8 haptics"
PARAM_DESC[FORCE_RETRAIN]="true|false — retrain EMG classifier"
PARAM_DESC[AUTO_KILL_S]="seconds before auto-kill (0 = never)"
PARAM_DESC[CONFIG_PATH]="path to YAML config file"

# ── ANSI helpers ─────────────────────────────────────────────────────
BOLD="$(printf '\e[1m')"; DIM="$(printf '\e[2m')"; REV="$(printf '\e[7m')"
RESET="$(printf '\e[0m')"
hide_cursor() { printf '\e[?25l'; }
show_cursor() { printf '\e[?25h'; }
clear_screen() { printf '\e[H\e[J'; }

read_key() {
    local key
    IFS= read -rsn1 key 2>/dev/null || { echo "q"; return; }
    if [[ $key == $'\e' ]]; then
        IFS= read -rsn2 -t 0.001 key 2>/dev/null || true
        case "$key" in '[A') echo UP ;; '[B') echo DOWN ;; *) echo ESC ;; esac
    elif [[ $key == '' ]]; then
        echo ENTER
    else
        echo "$key"
    fi
}

edit_param() {
    local varname="${PARAMS[$1]}"
    local old_val="${!varname}"
    local desc="${PARAM_DESC[$varname]}"
    printf '\e[J'
    printf "\n  Editing ${BOLD}%s${RESET} (%s)\n" "$varname" "$desc"
    printf "  Current: %s\n" "$old_val"
    printf "  New value: "
    show_cursor
    read -r new_val
    hide_cursor
    if [ -n "$new_val" ]; then
        printf -v "$varname" '%s' "$new_val"
    fi
}

draw_menu() {
    local sel=$1
    clear_screen
    echo "╭──────────────────────────────────────────────────────────╮"
    printf "│          ${BOLD}Option 4 — Haptic Force Test${RESET}                        │\n"
    echo "├──────────────────────────────────────────────────────────┤"
    printf "│  ${DIM}space${RESET}=start  ${DIM}e${RESET}=edit  ${DIM}↑↓${RESET}=navigate  ${DIM}q${RESET}=quit                     │\n"
    echo "╰──────────────────────────────────────────────────────────╯"
    echo ""
    for ((i=0; i<NUM_PARAMS; i++)); do
        local varname="${PARAMS[$i]}"
        local val="${!varname}"
        local desc="${PARAM_DESC[$varname]}"
        if [ "$i" -eq "$sel" ]; then
            printf "  ${REV} %-18s %-20s ${RESET} ${DIM}%s${RESET}\n" "$varname" "$val" "$desc"
        else
            printf "   %-18s %-20s  ${DIM}%s${RESET}\n" "$varname" "$val" "$desc"
        fi
    done
    echo ""
    printf "  ${DIM}Env overrides take precedence.  q to abort.${RESET}\n"
}

run_menu() {
    local sel=0
    hide_cursor
    trap 'show_cursor; printf "\n"; exit 0' INT TERM
    while true; do
        draw_menu "$sel"
        local key; key=$(read_key)
        case "$key" in
            UP)    sel=$(( (sel - 1 + NUM_PARAMS) % NUM_PARAMS )) ;;
            DOWN)  sel=$(( (sel + 1) % NUM_PARAMS )) ;;
            e|E)   edit_param "$sel" ;;
            ' '|ENTER)
                local tmpfile="/tmp/haptic_test_env.sh.$$"
                {
                    echo "#!/bin/bash"
                    echo "# Generated by menu_haptic_test.sh"
                    for ((i=0; i<NUM_PARAMS; i++)); do
                        local varname="${PARAMS[$i]}"
                        echo "export $varname='${!varname}'"
                    done
                } > "$tmpfile"
                cp "$tmpfile" /tmp/haptic_test_env.sh 2>/dev/null || true
                clear_screen
                show_cursor
                echo "Starting with:"
                for ((i=0; i<NUM_PARAMS; i++)); do
                    local varname="${PARAMS[$i]}"
                    printf "  %-18s = %s\n" "$varname" "${!varname}"
                done
                return 0
                ;;
            q|Q)
                clear_screen; show_cursor; echo "Aborted."; return 1 ;;
        esac
    done
}

run_menu
