int32 target_closure_percent  # Target grasp closure, in percentage
int32 spe_for_percent         # Grasp speed/force, in percentage
---
int32[3] mpos       # Final motor positions. 0: thumb, 1: index, 2: mrl.
string err_message  # Error message, in case of failure
---
int32[3] current_mpos  # Current motor positions. 0: thumb, 1: index, 2: mrl.
int32[3] current_mspe  # Current motor speeds. 0: thumb, 1: index, 2: mrl.
int32[3] current_nfor  # Current finger normal forces. 0: thumb, 1: index, 2: mrl.
int32[3] current_tfor  # Current finger tangential forces. 0: thumb, 1: index, 2: mrl.
