<?xml version="1.0"?>
<package format="3">
  <name>grasp_preshaping</name>
  <version>0.1.0</version>
  <description>Rust grasp preshaping compute library and core pipeline.</description>
  <maintainer email="daniel@example.com">Daniel</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
