set(_AMENT_PACKAGE_NAME "sensor_fusion_bringup")
set(sensor_fusion_bringup_VERSION "0.0.1")
set(sensor_fusion_bringup_MAINTAINER "TheRobotSkier <ebenne22@student.aau.dk>")
set(sensor_fusion_bringup_BUILD_DEPENDS )
set(sensor_fusion_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(sensor_fusion_bringup_BUILD_EXPORT_DEPENDS )
set(sensor_fusion_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(sensor_fusion_bringup_EXEC_DEPENDS "launch" "launch_ros" "imu_driver" "rclpy" "sensor_msgs" "geometry_msgs" "nav_msgs" "std_msgs" "std_srvs" "rosbag2_py" "rosidl_runtime_py" "sensor_fusion_msgs" "tf2_ros" "cv_bridge")
set(sensor_fusion_bringup_TEST_DEPENDS "ament_cmake_pytest")
set(sensor_fusion_bringup_GROUP_DEPENDS )
set(sensor_fusion_bringup_MEMBER_OF_GROUPS )
set(sensor_fusion_bringup_DEPRECATED "")
set(sensor_fusion_bringup_EXPORT_TAGS)
list(APPEND sensor_fusion_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
